// Generated by https://github.com/bcrist/microbe-regz
const Mmio = @import("microbe").Mmio;

pub const InterruptBitmap = packed struct(u32) {
    TIMER_IRQ_0: u1 = 0,
    TIMER_IRQ_1: u1 = 0,
    TIMER_IRQ_2: u1 = 0,
    TIMER_IRQ_3: u1 = 0,
    PWM_IRQ_WRAP: u1 = 0,
    USBCTRL_IRQ: u1 = 0,
    XIP_IRQ: u1 = 0,
    PIO0_IRQ_0: u1 = 0,
    PIO0_IRQ_1: u1 = 0,
    PIO1_IRQ_0: u1 = 0,
    PIO1_IRQ_1: u1 = 0,
    DMA_IRQ_0: u1 = 0,
    DMA_IRQ_1: u1 = 0,
    IO_IRQ_BANK0: u1 = 0,
    IO_IRQ_QSPI: u1 = 0,
    SIO_IRQ_PROC0: u1 = 0,
    SIO_IRQ_PROC1: u1 = 0,
    CLOCKS_IRQ: u1 = 0,
    SPI0_IRQ: u1 = 0,
    SPI1_IRQ: u1 = 0,
    UART0_IRQ: u1 = 0,
    UART1_IRQ: u1 = 0,
    ADC_IRQ_FIFO: u1 = 0,
    I2C0_IRQ: u1 = 0,
    I2C1_IRQ: u1 = 0,
    RTC_IRQ: u1 = 0,
    _reserved_1a: u6 = 0,
};

pub const SYSTICK = extern struct {
    CSR: Mmio(packed struct(u32) {
        ENABLE: enum(u1) {
            disabled = 0x0,
            enabled = 0x1,
        } = .disabled,
        TICKINT: enum(u1) {
            interrupt_disabled = 0x0,
            interrupt_enabled = 0x1,
        } = .interrupt_disabled,
        CLKSOURCE: enum(u1) {
            watchdog_tick = 0x0,
            clk_ref = 0x1,
        } = .watchdog_tick,
        _reserved_3: u13 = 0,
        COUNTFLAG: enum(u1) {
            waiting = 0x0,
            reached_zero = 0x1,
        } = .waiting,
        _reserved_11: u15 = 0,
    }, .rw),
    _reserved_4: [28]u8 = undefined,
    RVR: Mmio(packed struct(u32) {
        RELOAD: u24 = 0,
        _reserved_18: u8 = 0,
    }, .rw),
    _reserved_24: [28]u8 = undefined,
    CVR: Mmio(packed struct(u32) {
        CURRENT: u24 = 0,
        _reserved_18: u8 = 0,
    }, .rw),
    _reserved_44: [28]u8 = undefined,
    CALIB: Mmio(packed struct(u32) {
        TENMS: u24 = 0,
        _reserved_18: u6 = 0,
        SKEW: u1 = 0,
        NOREF: u1 = 0,
    }, .r),
};

pub const SCB = extern struct {
    CPUID: Mmio(packed struct(u32) {
        REVISION: u4 = 1,
        PARTNO: u12 = 0xC60,
        ARCHITECTURE: u4 = 0xC,
        VARIANT: u4 = 0,
        IMPLEMENTER: u8 = 0x41,
    }, .r),
    _reserved_4: [24]u8 = undefined,
    SHPR2: Mmio(packed struct(u32) {
        _reserved_0: u24 = 0,
        SVCALLPRI: u8 = 0,
    }, .rw),
    ICSR: Mmio(packed struct(u32) {
        VECTACTIVE: u9 = 0,
        _reserved_9: u3 = 0,
        VECTPENDING: u9 = 0,
        _reserved_15: u1 = 0,
        ISRPENDING: u1 = 0,
        ISRPREEMPT: u1 = 0,
        _reserved_18: u1 = 0,
        PENDSTCLR: u1 = 0,
        PENDSTSET: u1 = 0,
        PENDSVCLR: u1 = 0,
        PENDSVSET: u1 = 0,
        _reserved_1d: u2 = 0,
        NMIPENDSET: u1 = 0,
    }, .rw),
    _reserved_24: [24]u8 = undefined,
    SHPR3: Mmio(packed struct(u32) {
        _reserved_0: u16 = 0,
        PENDSVPRI: u8 = 0,
        SYSTICKPRI: u8 = 0,
    }, .rw),
    VTOR: Mmio(packed struct(u32) {
        _reserved_0: u8 = 0,
        TBLOFF: u24 = 0,
    }, .rw),
    _reserved_44: [24]u8 = undefined,
    SHCSR: Mmio(packed struct(u32) {
        _reserved_0: u15 = 0,
        SVCALL: u1 = 0,
        _reserved_10: u16 = 0,
    }, .rw),
    AIRCR: Mmio(packed struct(u32) {
        _reserved_0: u1 = 0,
        VECTCLRACTIVE: u1 = 0,
        SYSRESETREQ: u1 = 0,
        _reserved_3: u12 = 0,
        ENDIANESS: u1 = 0,
        VECTKEY: u16 = 0,
    }, .rw),
    _reserved_64: [28]u8 = undefined,
    SCR: Mmio(packed struct(u32) {
        _reserved_0: u1 = 0,
        SLEEPONEXIT: u1 = 0,
        SLEEPDEEP: u1 = 0,
        _reserved_3: u1 = 0,
        SEVONPEND: u1 = 0,
        _reserved_5: u27 = 0,
    }, .rw),
    _reserved_84: [28]u8 = undefined,
    CCR: Mmio(packed struct(u32) {
        _reserved_0: u3 = 0,
        UNALIGN_TRP: u1 = 0,
        _reserved_4: u5 = 0,
        STKALIGN: u1 = 0,
        _reserved_a: u22 = 0,
    }, .r),
};

pub const MPU = extern struct {
    TYPE: Mmio(packed struct(u32) {
        SEPARATE: u1 = 0,
        _reserved_1: u7 = 0,
        DREGION: u8 = 0,
        IREGION: u8 = 0,
        _reserved_18: u8 = 0,
    }, .r),
    _reserved_4: [28]u8 = undefined,
    CTRL: Mmio(packed struct(u32) {
        ENABLE: u1 = 0,
        HFNMIENA: u1 = 0,
        PRIVDEFENA: u1 = 0,
        _reserved_3: u29 = 0,
    }, .rw),
    _reserved_24: [28]u8 = undefined,
    RNR: Mmio(packed struct(u32) {
        REGION: u4 = 0,
        _reserved_4: u28 = 0,
    }, .rw),
    _reserved_44: [28]u8 = undefined,
    RBAR: Mmio(packed struct(u32) {
        REGION: u4 = 0,
        VALID: u1 = 0,
        _reserved_5: u3 = 0,
        ADDR: u24 = 0,
    }, .rw),
    _reserved_64: [28]u8 = undefined,
    RASR: Mmio(packed struct(u32) {
        ENABLE: u1 = 0,
        SIZE: u5 = 0,
        _reserved_6: u2 = 0,
        SRD: u8 = 0,
        B: u1 = 0,
        C: u1 = 0,
        S: u1 = 0,
        _reserved_13: u5 = 0,
        AP: u3 = 0,
        _reserved_1b: u1 = 0,
        XN: u1 = 0,
        _reserved_1d: u3 = 0,
    }, .rw),
};

pub const NVIC = extern struct {
    /// Interrupt Set Enable Register
    ISER: Mmio(InterruptBitmap, .rw),
    _reserved_4: [124]u8 = undefined,
    /// Interrupt Clear Enable Register
    ICER: Mmio(InterruptBitmap, .rw),
    _reserved_84: [124]u8 = undefined,
    /// Interrupt Set Pending Register
    ISPR: Mmio(InterruptBitmap, .rw),
    _reserved_104: [124]u8 = undefined,
    /// Interrupt Clear Pending Register
    ICPR: Mmio(InterruptBitmap, .rw),
    _reserved_184: [636]u8 = undefined,
    /// Interrupt Priority Register
    IPR0: Mmio(packed struct(u32) {
        TIMER_IRQ_0: u8 = 0,
        TIMER_IRQ_1: u8 = 0,
        TIMER_IRQ_2: u8 = 0,
        TIMER_IRQ_3: u8 = 0,
    }, .rw),
    /// Interrupt Priority Register
    IPR1: Mmio(packed struct(u32) {
        PWM_IRQ_WRAP: u8 = 0,
        USBCTRL_IRQ: u8 = 0,
        XIP_IRQ: u8 = 0,
        PIO0_IRQ_0: u8 = 0,
    }, .rw),
    /// Interrupt Priority Register
    IPR2: Mmio(packed struct(u32) {
        PIO0_IRQ_1: u8 = 0,
        PIO1_IRQ_0: u8 = 0,
        PIO1_IRQ_1: u8 = 0,
        DMA_IRQ_0: u8 = 0,
    }, .rw),
    /// Interrupt Priority Register
    IPR3: Mmio(packed struct(u32) {
        DMA_IRQ_1: u8 = 0,
        IO_IRQ_BANK0: u8 = 0,
        IO_IRQ_QSPI: u8 = 0,
        SIO_IRQ_PROC0: u8 = 0,
    }, .rw),
    /// Interrupt Priority Register
    IPR4: Mmio(packed struct(u32) {
        SIO_IRQ_PROC1: u8 = 0,
        CLOCKS_IRQ: u8 = 0,
        SPI0_IRQ: u8 = 0,
        SPI1_IRQ: u8 = 0,
    }, .rw),
    /// Interrupt Priority Register
    IPR5: Mmio(packed struct(u32) {
        UART0_IRQ: u8 = 0,
        UART1_IRQ: u8 = 0,
        ADC_IRQ_FIFO: u8 = 0,
        I2C0_IRQ: u8 = 0,
    }, .rw),
    /// Interrupt Priority Register
    IPR6: Mmio(packed struct(u32) {
        I2C1_IRQ: u8 = 0,
        RTC_IRQ: u8 = 0,
        _reserved_10: u16 = 0,
    }, .rw),
};
