// Generated by https://github.com/bcrist/microbe-regz
const Mmio = @import("microbe").Mmio;

pub const DriveStrength = enum(u2) {
    @"2mA" = 0,
    @"4mA" = 1,
    @"8mA" = 2,
    @"12mA" = 3,
};

pub const SlewRate = enum(u1) {
    slow = 0,
    fast = 1,
};

pub const PinMaintenance = enum(u2) {
    float = 0,
    pull_down = 1,
    pull_up = 2,
    _,
};

pub const ModeOverride = enum(u2) {
    normal = 0,
    invert = 1,
    force_low = 2,
    force_high = 3,
};

pub const VoltageSelect = packed struct(u32) {
    voltage: enum(u1) {
        @"3v3" = 0,
        @"1v8" = 1,
    } = .@"3v3",
    _reserved_1: u31 = 0,
};

pub const PADS = extern struct {
    voltage: Mmio(VoltageSelect, .rw),
    gpio: [30]Mmio(packed struct(u32) {
        speed: SlewRate = .slow,
        hysteresis: bool = true,
        maintenance: PinMaintenance = .pull_down,
        strength: DriveStrength = .@"4mA",
        input_enabled: bool = true,
        output_disabled: bool = false,
        _reserved_8: u24 = 0,
    }, .rw),
    swclk: Mmio(packed struct(u32) {
        speed: SlewRate = .slow,
        hysteresis: bool = true,
        maintenance: PinMaintenance = .pull_up,
        strength: DriveStrength = .@"4mA",
        input_enabled: bool = true,
        output_disabled: bool = true,
        _reserved_8: u24 = 0,
    }, .rw),
    swdio: Mmio(packed struct(u32) {
        speed: SlewRate = .slow,
        hysteresis: bool = true,
        maintenance: PinMaintenance = .pull_up,
        strength: DriveStrength = .@"4mA",
        input_enabled: bool = true,
        output_disabled: bool = false,
        _reserved_8: u24 = 0,
    }, .rw),
};

pub const PADS_QSPI = extern struct {
    voltage: Mmio(VoltageSelect, .rw),
    sclk: Mmio(packed struct(u32) {
        speed: SlewRate = .slow,
        hysteresis: bool = true,
        maintenance: PinMaintenance = .pull_down,
        strength: DriveStrength = .@"4mA",
        input_enabled: bool = true,
        output_disabled: bool = false,
        _reserved_8: u24 = 0,
    }, .rw),
    sd: [4]Mmio(packed struct(u32) {
        speed: SlewRate = .slow,
        hysteresis: bool = true,
        maintenance: PinMaintenance = .float,
        strength: DriveStrength = .@"4mA",
        input_enabled: bool = true,
        output_disabled: bool = false,
        _reserved_8: u24 = 0,
    }, .rw),
    ss: Mmio(packed struct(u32) {
        speed: SlewRate = .slow,
        hysteresis: bool = true,
        maintenance: PinMaintenance = .pull_up,
        strength: DriveStrength = .@"4mA",
        input_enabled: bool = true,
        output_disabled: bool = false,
        _reserved_8: u24 = 0,
    }, .rw),
};

pub const IoStatus = packed struct(u32) {
    _reserved_0: u8 = 0,

    /// Before override/inversion
    output_internal: u1 = 0,

    /// After override/inversion
    output_pad: u1 = 0,

    _reserved_a: u2 = 0,

    /// Before override/inversion
    oe_internal: u1 = 0,

    /// After override/inversion
    oe_pad: u1 = 0,

    _reserved_e: u3 = 0,

    /// Before override/inversion
    input_pad: u1 = 0,

    _reserved_12: u1 = 0,

    /// After override/inversion
    input_internal: u1 = 0,

    _reserved_14: u4 = 0,

    /// Before override/inversion
    irq_pad: u1 = 0,

    _reserved_19: u1 = 0,

    /// After override/inversion
    irq_internal: u1 = 0,

    _reserved_1b: u5 = 0,
};

pub const IoFunction = enum(u5) {
    jtag = 0x0,
    spi = 0x1,
    uart = 0x2,
    i2c = 0x3,
    pwm = 0x4,
    sio = 0x5,
    pio0 = 0x6,
    pio1 = 0x7,
    clock = 0x8,
    usb = 0x9,
    disable = 0x1F,
    _,
};

pub const QspiFunction = enum(u5) {
    ssi = 0x0,
    sio = 0x5,
    disable = 0x1F,
    _,
};

pub const QspiStatusControl = extern struct {
    status: Mmio(IoStatus, .rw),
    control: Mmio(packed struct(u32) {
        func: QspiFunction = .disable,
        _reserved_5: u3 = 0,
        output_override: ModeOverride = .normal,
        _reserved_a: u2 = 0,
        oe_override: ModeOverride = .normal,
        _reserved_e: u2 = 0,
        input_override: ModeOverride = .normal,
        _reserved_12: u10 = 0,
        irq_override: ModeOverride = .normal,
        _reserved_1e: u2 = 0,
    }, .rw),
};

pub const IO = [30]extern struct {
    status: Mmio(IoStatus, .rw),
    control: Mmio(packed struct(u32) {
        func: IoFunction = .disable,
        _reserved_5: u3 = 0,
        output_override: ModeOverride = .normal,
        _reserved_a: u2 = 0,
        oe_override: ModeOverride = .normal,
        _reserved_e: u2 = 0,
        input_override: ModeOverride = .normal,
        _reserved_12: u10 = 0,
        irq_override: ModeOverride = .normal,
        _reserved_1e: u2 = 0,
    }, .rw),
};

pub const IO_QSPI = extern struct {
    sclk: QspiStatusControl,
    ss: QspiStatusControl,
    sd: [4]QspiStatusControl,
};

pub const InterruptBitmap0 = packed struct(u32) {
    gpio0_low: bool = false,
    gpio0_high: bool = false,
    gpio0_falling: bool = false,
    gpio0_rising: bool = false,
    gpio1_low: bool = false,
    gpio1_high: bool = false,
    gpio1_falling: bool = false,
    gpio1_rising: bool = false,
    gpio2_low: bool = false,
    gpio2_high: bool = false,
    gpio2_falling: bool = false,
    gpio2_rising: bool = false,
    gpio3_low: bool = false,
    gpio3_high: bool = false,
    gpio3_falling: bool = false,
    gpio3_rising: bool = false,
    gpio4_low: bool = false,
    gpio4_high: bool = false,
    gpio4_falling: bool = false,
    gpio4_rising: bool = false,
    gpio5_low: bool = false,
    gpio5_high: bool = false,
    gpio5_falling: bool = false,
    gpio5_rising: bool = false,
    gpio6_low: bool = false,
    gpio6_high: bool = false,
    gpio6_falling: bool = false,
    gpio6_rising: bool = false,
    gpio7_low: bool = false,
    gpio7_high: bool = false,
    gpio7_falling: bool = false,
    gpio7_rising: bool = false,
};

pub const InterruptBitmap1 = packed struct(u32) {
    gpio8_low: bool = false,
    gpio8_high: bool = false,
    gpio8_falling: bool = false,
    gpio8_rising: bool = false,
    gpio9_low: bool = false,
    gpio9_high: bool = false,
    gpio9_falling: bool = false,
    gpio9_rising: bool = false,
    gpio10_low: bool = false,
    gpio10_high: bool = false,
    gpio10_falling: bool = false,
    gpio10_rising: bool = false,
    gpio11_low: bool = false,
    gpio11_high: bool = false,
    gpio11_falling: bool = false,
    gpio11_rising: bool = false,
    gpio12_low: bool = false,
    gpio12_high: bool = false,
    gpio12_falling: bool = false,
    gpio12_rising: bool = false,
    gpio13_low: bool = false,
    gpio13_high: bool = false,
    gpio13_falling: bool = false,
    gpio13_rising: bool = false,
    gpio14_low: bool = false,
    gpio14_high: bool = false,
    gpio14_falling: bool = false,
    gpio14_rising: bool = false,
    gpio15_low: bool = false,
    gpio15_high: bool = false,
    gpio15_falling: bool = false,
    gpio15_rising: bool = false,
};

pub const InterruptBitmap2 = packed struct(u32) {
    gpio16_low: bool = false,
    gpio16_high: bool = false,
    gpio16_falling: bool = false,
    gpio16_rising: bool = false,
    gpio17_low: bool = false,
    gpio17_high: bool = false,
    gpio17_falling: bool = false,
    gpio17_rising: bool = false,
    gpio18_low: bool = false,
    gpio18_high: bool = false,
    gpio18_falling: bool = false,
    gpio18_rising: bool = false,
    gpio19_low: bool = false,
    gpio19_high: bool = false,
    gpio19_falling: bool = false,
    gpio19_rising: bool = false,
    gpio20_low: bool = false,
    gpio20_high: bool = false,
    gpio20_falling: bool = false,
    gpio20_rising: bool = false,
    gpio21_low: bool = false,
    gpio21_high: bool = false,
    gpio21_falling: bool = false,
    gpio21_rising: bool = false,
    gpio22_low: bool = false,
    gpio22_high: bool = false,
    gpio22_falling: bool = false,
    gpio22_rising: bool = false,
    gpio23_low: bool = false,
    gpio23_high: bool = false,
    gpio23_falling: bool = false,
    gpio23_rising: bool = false,
};

pub const InterruptBitmap3 = packed struct(u32) {
    gpio24_low: bool = false,
    gpio24_high: bool = false,
    gpio24_falling: bool = false,
    gpio24_rising: bool = false,
    gpio25_low: bool = false,
    gpio25_high: bool = false,
    gpio25_falling: bool = false,
    gpio25_rising: bool = false,
    gpio26_low: bool = false,
    gpio26_high: bool = false,
    gpio26_falling: bool = false,
    gpio26_rising: bool = false,
    gpio27_low: bool = false,
    gpio27_high: bool = false,
    gpio27_falling: bool = false,
    gpio27_rising: bool = false,
    gpio28_low: bool = false,
    gpio28_high: bool = false,
    gpio28_falling: bool = false,
    gpio28_rising: bool = false,
    gpio29_low: bool = false,
    gpio29_high: bool = false,
    gpio29_falling: bool = false,
    gpio29_rising: bool = false,
    _reserved_18: u8 = 0,
};

pub const InterruptBitmap = extern struct {
    gpio_0_to_7: Mmio(InterruptBitmap0, .rw),
    gpio_8_to_15: Mmio(InterruptBitmap1, .rw),
    gpio_16_to_23: Mmio(InterruptBitmap2, .rw),
    gpio_24_to_29: Mmio(InterruptBitmap3, .rw),
};

pub const InterruptEnableForceStatus = extern struct {
    enable: InterruptBitmap,
    force: InterruptBitmap,
    status: extern struct {
        gpio_0_to_7: Mmio(InterruptBitmap0, .r),
        gpio_8_to_15: Mmio(InterruptBitmap1, .r),
        gpio_16_to_23: Mmio(InterruptBitmap2, .r),
        gpio_24_to_29: Mmio(InterruptBitmap3, .r),
    },
};

pub const IO_INT = extern struct {
    /// Write 1 to clear edge interrupt flags
    interrupt_status: InterruptBitmap,

    core0: InterruptEnableForceStatus,
    core1: InterruptEnableForceStatus,
    dormant_wake: InterruptEnableForceStatus,
};

pub const QspiInterruptBitmap = packed struct(u32) {
    sclk_low: bool = false,
    sclk_high: bool = false,
    sclk_falling: bool = false,
    sclk_rising: bool = false,
    ss_low: bool = false,
    ss_high: bool = false,
    ss_falling: bool = false,
    ss_rising: bool = false,
    sd0_low: bool = false,
    sd0_high: bool = false,
    sd0_falling: bool = false,
    sd0_rising: bool = false,
    sd1_low: bool = false,
    sd1_high: bool = false,
    sd1_falling: bool = false,
    sd1_rising: bool = false,
    sd2_low: bool = false,
    sd2_high: bool = false,
    sd2_falling: bool = false,
    sd2_rising: bool = false,
    sd3_low: bool = false,
    sd3_high: bool = false,
    sd3_falling: bool = false,
    sd3_rising: bool = false,
    _reserved_18: u8 = 0,
};

pub const QspiInterruptEnableForceStatus = extern struct {
    enable: Mmio(QspiInterruptBitmap, .rw),
    force: Mmio(QspiInterruptBitmap, .rw),
    status: Mmio(QspiInterruptBitmap, .r),
};

pub const IO_QSPI_INT = extern struct {
    /// Write 1 to clear edge interrupt flags
    interrupt_status: Mmio(QspiInterruptBitmap, .rw),

    core0: QspiInterruptEnableForceStatus,
    core1: QspiInterruptEnableForceStatus,
    dormant_wake: QspiInterruptEnableForceStatus,
};
