// Generated by https://github.com/bcrist/microbe-regz
const microbe = @import("microbe");
const chip = @import("chip");
const MMIO = microbe.MMIO;

pub const SPI = extern struct {
    SSPCR0: MMIO(packed struct(u32) {
        DSS: u4 = 0,
        FRF: u2 = 0,
        SPO: u1 = 0,
        SPH: u1 = 0,
        SCR: u8 = 0,
        _reserved_10: u16 = 0,
    }, .rw),
    SSPCR1: MMIO(packed struct(u32) {
        LBM: u1 = 0,
        SSE: u1 = 0,
        MS: u1 = 0,
        SOD: u1 = 0,
        _reserved_4: u28 = 0,
    }, .rw),
    SSPDR: MMIO(packed struct(u32) {
        DATA: u16 = 0,
        _reserved_10: u16 = 0,
    }, .rw),
    SSPSR: MMIO(packed struct(u32) {
        TFE: u1 = 1,
        TNF: u1 = 1,
        RNE: u1 = 0,
        RFF: u1 = 0,
        BSY: u1 = 0,
        _reserved_5: u27 = 0,
    }, .rw),
    SSPCPSR: MMIO(packed struct(u32) {
        CPSDVSR: u8 = 0,
        _reserved_8: u24 = 0,
    }, .rw),
    SSPIMSC: MMIO(packed struct(u32) {
        RORIM: u1 = 0,
        RTIM: u1 = 0,
        RXIM: u1 = 0,
        TXIM: u1 = 0,
        _reserved_4: u28 = 0,
    }, .rw),
    SSPRIS: MMIO(packed struct(u32) {
        RORRIS: u1 = 0,
        RTRIS: u1 = 0,
        RXRIS: u1 = 0,
        TXRIS: u1 = 1,
        _reserved_4: u28 = 0,
    }, .rw),
    SSPMIS: MMIO(packed struct(u32) {
        RORMIS: u1 = 0,
        RTMIS: u1 = 0,
        RXMIS: u1 = 0,
        TXMIS: u1 = 0,
        _reserved_4: u28 = 0,
    }, .rw),
    SSPICR: MMIO(packed struct(u32) {
        RORIC: u1 = 0,
        RTIC: u1 = 0,
        _reserved_2: u30 = 0,
    }, .rw),
    SSPDMACR: MMIO(packed struct(u32) {
        RXDMAE: u1 = 0,
        TXDMAE: u1 = 0,
        _reserved_2: u30 = 0,
    }, .rw),
    _reserved_28: [4024]u8 = undefined,
    SSPPERIPHID0: MMIO(packed struct(u32) {
        PARTNUMBER0: u8 = 0x22,
        _reserved_8: u24 = 0,
    }, .rw),
    SSPPERIPHID1: MMIO(packed struct(u32) {
        PARTNUMBER1: u4 = 0,
        DESIGNER0: u4 = 1,
        _reserved_8: u24 = 0,
    }, .rw),
    SSPPERIPHID2: MMIO(packed struct(u32) {
        DESIGNER1: u4 = 4,
        REVISION: u4 = 3,
        _reserved_8: u24 = 0,
    }, .rw),
    SSPPERIPHID3: MMIO(packed struct(u32) {
        CONFIGURATION: u8 = 0,
        _reserved_8: u24 = 0,
    }, .rw),
    SSPPCELLID0: MMIO(packed struct(u32) {
        SSPPCELLID0: u8 = 0xD,
        _reserved_8: u24 = 0,
    }, .rw),
    SSPPCELLID1: MMIO(packed struct(u32) {
        SSPPCELLID1: u8 = 0xF0,
        _reserved_8: u24 = 0,
    }, .rw),
    SSPPCELLID2: MMIO(packed struct(u32) {
        SSPPCELLID2: u8 = 5,
        _reserved_8: u24 = 0,
    }, .rw),
    SSPPCELLID3: MMIO(packed struct(u32) {
        SSPPCELLID3: u8 = 0xB1,
        _reserved_8: u24 = 0,
    }, .rw),
};
